<a href="https://colab.research.google.com/github/19pa1a0207/AI-Lab/blob/master/Exp_1_numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Experiment1:Numpy

1)Different ways to create a Numpy arrays.

In [ ]:
import numpy as np
x = np.array([1,2,3])
print(x)

[1 2 3]


In [ ]:
y = np.array([[4,5,6],[7,8,9]])
print(y)

[[4 5 6]
 [7 8 9]]


2)Add, remove, modify elements in an array.

#Add

In [ ]:
b = np.append(y,[6,4,2])
print(b)

[4 5 6 7 8 9 6 4 2]


#Remove

In [ ]:
newarray = np.delete(x,2)
print(newarray)

[1 2]


#Modify

In [ ]:
b = np.array([6,4,1,3,5,9])
b[b<2] = -1
print(b)

[ 6  4 -1  3  5  9]


3)Arthematic operations on Numpy array

In [ ]:
import numpy as np
s = np.random.random((4,4))
r = np.random.random((4,4))
sum = np.add(s,r)
print(sum)


[[0.95746686 0.53000873 0.09149287 0.69591489]
 [1.20057266 1.00187443 0.80714105 1.76300536]
 [0.57169605 0.19533788 0.93876407 0.1881297 ]
 [0.53105356 1.33058666 0.27363351 0.55906882]]


In [ ]:
diff = np.subtract(s,r)
print(diff)

[[ 0.03905133  0.40542303 -0.0797136  -0.28710546]
 [-0.40429899 -0.35819192 -0.26115771 -0.048522  ]
 [ 0.56445215 -0.08030391  0.93270295 -0.0833267 ]
 [-0.1413906  -0.48765619 -0.17447006 -0.34061502]]


In [ ]:
prod = np.multiply(s,r)
print(s,r)

[[0.4982591  0.46771588 0.00588964 0.20440471]
 [0.39813684 0.32184126 0.27299167 0.85724168]
 [0.5680741  0.05751698 0.93573351 0.0524015 ]
 [0.19483148 0.42146524 0.04958172 0.1092269 ]] [[0.45920777 0.06229285 0.08560323 0.49151017]
 [0.80243583 0.68003318 0.53414938 0.90576368]
 [0.00362195 0.1378209  0.00303056 0.1357282 ]
 [0.33622208 0.90912142 0.22405178 0.44984192]]


In [ ]:
quo = np.multiply(s,r)
print(s,r)

[[0.4982591  0.46771588 0.00588964 0.20440471]
 [0.39813684 0.32184126 0.27299167 0.85724168]
 [0.5680741  0.05751698 0.93573351 0.0524015 ]
 [0.19483148 0.42146524 0.04958172 0.1092269 ]] [[0.45920777 0.06229285 0.08560323 0.49151017]
 [0.80243583 0.68003318 0.53414938 0.90576368]
 [0.00362195 0.1378209  0.00303056 0.1357282 ]
 [0.33622208 0.90912142 0.22405178 0.44984192]]


In [ ]:
mod = np.mod(s,r)
print(mod)

[[0.03905133 0.03166595 0.00588964 0.20440471]
 [0.39813684 0.32184126 0.27299167 0.85724168]
 [0.00305017 0.05751698 0.00231978 0.0524015 ]
 [0.19483148 0.42146524 0.04958172 0.1092269 ]]


In [ ]:
power = np.power(s,r)
print(power)

[[0.72622149 0.9537669  0.64433596 0.45824662]
 [0.47758606 0.46257273 0.49982681 0.86977592]
 [0.99795387 0.67464295 0.99979872 0.67016051]
 [0.57698924 0.45589295 0.51013425 0.36931789]]


4)Slicing and iterating of numpy arrays.
slicing

In [ ]:
import numpy as np
arrays = np.array([1,2,3,4,5,6,7])
print(arrays[2:4])

[3 4]


iterating

In [ ]:
for y in arrays:
  print(y)

1
2
3
4
5
6
7


5)Matrix operation on numpy arrays.

In [ ]:
import numpy as np
a = np.array([[3,4],[1,2]])
b = np.array([[7,8],[5,6]])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))

[[10 12]
 [ 6  8]]
[[-4 -4]
 [-4 -4]]
[[0.42857143 0.5       ]
 [0.2        0.33333333]]
