<a href="https://colab.research.google.com/github/19pa1a0207/AI-Lab/blob/master/experiment_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Experiment No 1:Numpy

## 1) Differentways to create a Numpy arrays.

###a)Create a numpy array using list

In [ ]:
import numpy as np
a = np.array([2,3,4])
print(a)

[2 3 4]


###b)Create a numpy array using arange

In [ ]:
b = np.arange(8)
print(b)

[0 1 2 3 4 5 6 7]


## 2)Add,remove,modify elements in a array

### a)Add

In [ ]:
s = np.append(a,[2,5,7])
print(s)

[2 3 4 2 5 7]


### b)Remove

In [ ]:
p = np.delete(a,2)
print(p)

[2 3]


### c)Modify

In [ ]:
s = np.array([6,4,3,1,9,5])
s[s<2]=-1
print(s)

[ 6  4  3 -1  9  5]


## 3)Arthematic operations on Numpy array.

In [ ]:
 
import numpy as np
t = np.random.random((3,3))
r = np.random.random((3,3))
add = np.add(t,r)
sub = np.subtract(t,r)
mul = np.multiply(t,r)
div = np.divide(t,r)
mod = np.mod(t,r)
pow = np.power(t,r)
print(add)
print(sub)
print(mul)
print(div)
print(mod)
print(pow)

[[0.76401251 0.82651048 1.25357963]
 [1.39061471 1.36435034 0.90586037]
 [1.29168783 1.11383564 1.22496453]]
[[ 0.02330652  0.53747833  0.30216381]
 [ 0.52715702 -0.4214822  -0.41243293]
 [-0.08473014 -0.6020004  -0.42905414]]
[[0.14579298 0.09855915 0.37003973]
 [0.41397869 0.42095115 0.16262052]
 [0.41531957 0.21955634 0.32911266]]
[[1.06293057 4.71915959 1.63518769]
 [2.22103729 0.5279712  0.37429262]
 [0.87688312 0.29830079 0.48119795]]
[[0.02330652 0.10393012 0.30216381]
 [0.09542818 0.47143407 0.24671372]
 [0.60347885 0.25591762 0.3979552 ]]
[[0.70803016 0.94619066 0.88736861]
 [0.98203791 0.51096631 0.39752666]
 [0.70639831 0.31059788 0.46672292]]


## 4)Slicing and iterating of numpy arrays.

### a)slicing

In [ ]:
 
import numpy as np
arr = np.array([7,5,3,9,2,5])
print(arr[2:5])

[3 9 2]


### b) iterating

In [ ]:
 
for x in arr:
  print(x)

7
5
3
9
2
5


## 5)Matrix operation on numpy arrays.

In [ ]:
 
import numpy as np
d = np.array([[4,3],[2,1]])
v = np.array([[8,7],[6,5]])
print(np.add(d,v))
print(np.subtract(d,v))    
print(np.divide(d,v))

[[12 10]
 [ 8  6]]
[[-4 -4]
 [-4 -4]]
[[0.5        0.42857143]
 [0.33333333 0.2       ]]
